language: node_js
sudo: false

branches:
  only:
  - master

node_js:
  - "8"

before_install:
  - npm install -g vsce

install:
 - npm install
 - npm run vscode:prepublish

script:
  - env
  - `vsce publish -p ${MARKTABLE_EXTENSION_TOKEN}`

